
= team-f

== 開発環境
[cols="1,2", options="header"]
|===
|種類
|名前

|使用言語
|Python3.7

|形態素解析
|mecab

|係り受け解析
|cabocha

|コーディング規約
|PEP8

|Code Formatter
|Blackかautopep8

|Lint
|hacking

|統合開発環境
|Visual Studio Code

|ビルドツール
|bazel

|単体テスト用のライブラリ
|unittest(python標準)かpytest(単体テストフレームワーク)

|総合テスト用のCI
|GitHub Actions

|コードカバレッジ
|Code Coverage(pythonライブラリ)

|ブランチ管理の方針
|GitHub Flow
|===

==  Pythonのインストール

https://www.python.org/downloads/

上記のURLから自分のOSにあったpython3.7のパッケージをダウンロードする(最新版は3.7.7)。ダウンロードしたパッケージを実行し、インストールする。

または、Anacondaをインストールする。

https://www.anaconda.com/products/individual

上記のURLから自分のOSにあったpython3.7用のAnacondaのインストーラーをダウンロードする。インストーラーを実行してAnaconda本体(約3GB)をインストールする。インストールしたら、Anaconda Promptを実行するとbase環境（最初からある環境）でコマンドプロンプトが実行し、python(3.7.6)が使用できるようになる。また、Anaconda NavigatorでEnvironmentsタブをクリックし、createボタンで新しい環境を作成し、その環境で実行することもできる。
作成した環境で特定のバージョンのPythonをインストールしたい場合は、以下のコマンドで"python=3.7.7"のように指定する。 +
[source,windows]
----
conda install python=3.7.7
----

== エディタのインストール

VS Codeの導入
https://code.visualstudio.com/

上記のURLからダウンロードしたファイルを実行し、インストールする。

== プラグインの導入
https://code.visualstudio.com/docs/languages/python

上記のURLを参考にして導入する。

=== 最低限必要なもの
* Python +
Pythonの拡張機能を提供する

=== あると便利なもの
* Japanese Language Pack for VS Code +
VS Codeの言語を日本語化する
